min_particles: 80
max_particles: 200
kld_err: 0.02
update_min_d: 0.25
update_min_a: 0.2
resample_interval: 1
transform_tolerance: 1.0
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
gui_publish_rate: 50.0 # 50Hz initially
odom_model_type: omni
base_frame_id: base_link
global_frame_id: map
odom_frame_id: odom 

use_map_topic: true

laser_max_range: -1.0
laser_min_range: -1.0
laser_max_beams: 100
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

odom_alpha1: 0.2 # theta/theta
odom_alpha2: 0.5 # theta/rho
odom_alpha3: 0.05 # rho/rho
odom_alpha4: 0.5 # rho/theta
odom_alpha5: 0.2
